
on: [push]

jobs:
  custom_test:
    runs-on: windows-2019
    name: Test our custom action locally with act
    steps:
      - name: Compile AHK Script
        uses: bjesuiter/ahk-compile-action@master
        id: ahk-compile
        with:
          in_script: example.ahk
          out_exe: example.exe
      - name: Run the newly compiled exe
        run: example.exe