
on: [push]

jobs:
  custom_test:
    runs-on: windows-2019
    name: Test our custom action
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Compile AHK Script
        uses: bjesuiter/ahk-compile-action@main
        id: ahk_compile
        with:
          in_script: ${{github.workspace}}\example.ahk
          out_exe: ${{github.workspace}}\example.exe
        timeout-minutes: 5
      - name: Run the newly compiled exe
        run: ${{steps.ahk_compile.outputs.out_exe}}